
export const IMAGES = {
  accessories: [
    process.env.PUBLIC_URL + '/avatar/accessorie_1.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_2.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_3.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_4.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_5.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_6.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_7.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_8.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_9.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_10.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_11.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_12.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_13.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_14.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_15.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_16.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_17.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_18.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_19.png',
    process.env.PUBLIC_URL + '/avatar/accessorie_20.png'
  ],
  body: [
    process.env.PUBLIC_URL + '/avatar/body_1.png',
    process.env.PUBLIC_URL + '/avatar/body_2.png',
    process.env.PUBLIC_URL + '/avatar/body_3.png',
    process.env.PUBLIC_URL + '/avatar/body_4.png',
    process.env.PUBLIC_URL + '/avatar/body_5.png',
    process.env.PUBLIC_URL + '/avatar/body_6.png',
    process.env.PUBLIC_URL + '/avatar/body_7.png',
    process.env.PUBLIC_URL + '/avatar/body_8.png',
    process.env.PUBLIC_URL + '/avatar/body_9.png',
    process.env.PUBLIC_URL + '/avatar/body_10.png',
    process.env.PUBLIC_URL + '/avatar/body_11.png',
    process.env.PUBLIC_URL + '/avatar/body_12.png',
    process.env.PUBLIC_URL + '/avatar/body_13.png',
    process.env.PUBLIC_URL + '/avatar/body_14.png',
    process.env.PUBLIC_URL + '/avatar/body_15.png'
  ],
  eyes: [
    process.env.PUBLIC_URL + '/avatar/eyes_1.png',
    process.env.PUBLIC_URL + '/avatar/eyes_2.png',
    process.env.PUBLIC_URL + '/avatar/eyes_3.png',
    process.env.PUBLIC_URL + '/avatar/eyes_4.png',
    process.env.PUBLIC_URL + '/avatar/eyes_5.png',
    process.env.PUBLIC_URL + '/avatar/eyes_6.png',
    process.env.PUBLIC_URL + '/avatar/eyes_7.png',
    process.env.PUBLIC_URL + '/avatar/eyes_8.png',
    process.env.PUBLIC_URL + '/avatar/eyes_9.png',
    process.env.PUBLIC_URL + '/avatar/eyes_10.png',
    process.env.PUBLIC_URL + '/avatar/eyes_11.png',
    process.env.PUBLIC_URL + '/avatar/eyes_12.png',
    process.env.PUBLIC_URL + '/avatar/eyes_13.png',
    process.env.PUBLIC_URL + '/avatar/eyes_14.png',
    process.env.PUBLIC_URL + '/avatar/eyes_15.png'
  ],
  mouth: [
    process.env.PUBLIC_URL + '/avatar/mouth_1.png',
    process.env.PUBLIC_URL + '/avatar/mouth_2.png',
    process.env.PUBLIC_URL + '/avatar/mouth_3.png',
    process.env.PUBLIC_URL + '/avatar/mouth_4.png',
    process.env.PUBLIC_URL + '/avatar/mouth_5.png',
    process.env.PUBLIC_URL + '/avatar/mouth_6.png',
    process.env.PUBLIC_URL + '/avatar/mouth_7.png',
    process.env.PUBLIC_URL + '/avatar/mouth_8.png',
    process.env.PUBLIC_URL + '/avatar/mouth_9.png',
    process.env.PUBLIC_URL + '/avatar/mouth_10.png'
  ],
  fur: [
    process.env.PUBLIC_URL + '/avatar/fur_1.png',
    process.env.PUBLIC_URL + '/avatar/fur_2.png',
    process.env.PUBLIC_URL + '/avatar/fur_3.png',
    process.env.PUBLIC_URL + '/avatar/fur_4.png',
    process.env.PUBLIC_URL + '/avatar/fur_5.png',
    process.env.PUBLIC_URL + '/avatar/fur_6.png',
    process.env.PUBLIC_URL + '/avatar/fur_7.png',
    process.env.PUBLIC_URL + '/avatar/fur_8.png',
    process.env.PUBLIC_URL + '/avatar/fur_9.png',
    process.env.PUBLIC_URL + '/avatar/fur_10.png'
  ],
};

